name: tent_mapper_mobile
description: Seattle Tent Mapper mobile application for iOS and Android
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # Firebase
  firebase_core: ^2.24.2
  cloud_firestore: ^4.13.6
  firebase_storage: ^11.5.6
  firebase_auth: ^4.15.0
  
  # Map
  flutter_map: ^6.1.0
  latlong2: ^0.9.0
  
  # Location
  geolocator: ^10.1.0
  permission_handler: ^11.1.0
  
  # Camera & Images
  image_picker: ^1.0.7
  
  # UI
  cupertino_icons: ^1.0.6
  
  # HTTP for reCAPTCHA
  http: ^1.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/tent.png
    - assets/images/rv.png
    - assets/images/encampment.png
    - assets/images/structure.png

